services:
  minecraft-crossplay:
    image: itzg/minecraft-server:latest
    container_name: minecraft-crossplay
    restart: unless-stopped
    stdin_open: true
    tty: true

    ports:
      - "25565:25565/tcp"
      - "19132:19132/udp"

    environment:
      EULA: "TRUE"
      TZ: "America/Lima"

      TYPE: "PAPER"
      VERSION: "LATEST"

      MOTD: "Servidor EPIS | Java + Bedrock"
      SERVER_NAME: "Servidor EPIS"

      MODE: "survival"
      DIFFICULTY: "normal"
      MAX_PLAYERS: "20"

      MEMORY: "4G"

      ONLINE_MODE: "TRUE"
      ENABLE_WHITELIST: "FALSE"

      ALLOW_FLIGHT: "TRUE"
      PVP: "TRUE"
      SPAWN_PROTECTION: "0"

      VIEW_DISTANCE: "12"
      SIMULATION_DISTANCE: "8"

      ENABLE_RCON: "TRUE"
      RCON_PASSWORD: "CAMBIA_ESTA_CLAVE_POR_UNA_SEGURA"

      OVERRIDE_SERVER_PROPERTIES: "TRUE"

      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
        https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/build/libs/ViaVersion.jar

    volumes:
      - minecraft-crossplay-data:/data

volumes:
  minecraft-crossplay-data: