services:
  minecraft-bedrock:
    image: itzg/minecraft-bedrock-server:latest
    container_name: minecraft-bedrock
    restart: unless-stopped

    ports:
      - "19132:19132/udp"

    environment:
      EULA: "TRUE"
      VERSION: "LATEST"
      TZ: "America/Lima"
      ALLOW_LIST: "false"

      SERVER_NAME: "Servidor de EPIS"
      LEVEL_NAME: "Agua Dulce"

      GAMEMODE: "survival"
      DIFFICULTY: "normal"

      MAX_PLAYERS: "10"
      ONLINE_MODE: "true"
      ALLOW_CHEATS: "false"

      VIEW_DISTANCE: "24"
      TICK_DISTANCE: "8"

      DEFAULT_PLAYER_PERMISSION_LEVEL: "member"
      PLAYER_IDLE_TIMEOUT: "30"

    volumes:
      - minecraft-bedrock-data:/data

volumes:
  minecraft-bedrock-data: