services:
  minecraft-crossplay:
    image: itzg/minecraft-server:latest
    container_name: minecraft-crossplay
    restart: unless-stopped
    stdin_open: true
    tty: true

    ports:
      # Java Edition
      - "25565:25565/tcp"

      # Bedrock Edition (Geyser)
      - "19132:19132/udp"

    environment:
      EULA: "TRUE"

      TZ: "America/Lima"

      TYPE: "PAPER"

      VERSION: "LATEST"

      MEMORY: "4G"

      MOTD: "§aServidor EPIS §7| §bJava + Bedrock"

      MODE: "survival"

      DIFFICULTY: "normal"

      MAX_PLAYERS: "20"

      ONLINE_MODE: "TRUE"

      ENABLE_WHITELIST: "FALSE"

      ALLOW_FLIGHT: "TRUE"

      PVP: "TRUE"

      SPAWN_PROTECTION: "0"

      VIEW_DISTANCE: "12"

      SIMULATION_DISTANCE: "8"

      ENABLE_RCON: "TRUE"

      RCON_PORT: "25575"

      RCON_PASSWORD: "Minecraft2026!"

      OVERRIDE_SERVER_PROPERTIES: "TRUE"

      ENABLE_AUTOPAUSE: "FALSE"

      USE_AIKAR_FLAGS: "TRUE"

      JVM_XX_OPTS: "-XX:+UseG1GC"

      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot

    volumes:
      - minecraft-data:/data

volumes:
  minecraft-data: